### ISSUE TITLE
Feature Ask: Azure Cloud DNS Provider

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#130]
<a href="https://github.com/jpoon"><img src="https://avatars3.githubusercontent.com/u/85374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jpoon](https://github.com/jpoon)**
_Monday Apr 24, 2017 at 19:31 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/44874_

----

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:30Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux k8s-master-30143214-0 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: ACS
- **Others**:

As of 1.6, the current DNS providers are [AWS (Route53), CoreDNS, Google, (CloudDNS)](https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider/providers). The ask is to implement a DNS provider for Azure.

cc @xtophs @colemickens

**Comment by irfanurrehman** [comment]
<a href="https://github.com/spzala"><img src="https://avatars2.githubusercontent.com/u/6462877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spzala](https://github.com/spzala)**
_Thursday May 18, 2017 at 22:10 GMT_

----

area/dns

**Comment by irfanurrehman** [comment]
<a href="https://github.com/spzala"><img src="https://avatars2.githubusercontent.com/u/6462877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spzala](https://github.com/spzala)**
_Thursday May 18, 2017 at 22:10 GMT_

----

sig/network

**Comment by irfanurrehman** [comment]
cc @jpoon

**Comment by irfanurrehman** [comment]
Adding help wanted, with an info that @xtophs already did some work towards this [here](https://github.com/kubernetes/kubernetes/pull/51026), but the effort did not complete because of the repo move.

**Comment by xtophs** [comment]
PR coming next week. Nikola is helping with e2e Tests.

Sent from my iPhone

On Feb 2, 2018, at 7:01 AM, irfanurrehman <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding help wanted, with an info that @xtophs<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxtophs&data=02%7C01%7C%7C8e41c24fbfd54011a07c08d56a4dd389%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636531804846286532&sdata=%2F1wTa0XQYW%2FuRK3SkooOJa06KbNCsu1L46fyy3K6Sew%3D&reserved=0> already did some work towards this here<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fpull%2F51026&data=02%7C01%7C%7C8e41c24fbfd54011a07c08d56a4dd389%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636531804846286532&sdata=W33WomWLtI8B93XNCEOATtSfBhrOjVu8E%2FTQXIARccM%3D&reserved=0>, but the effort did not complete because of the repo move.

**Comment by irfanurrehman** [comment]
Amazing! thanks @xtophs for doing this.
