### ISSUE TITLE
Document using hosted DNS providers in non-cloud environments

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/federation#250]
We currently have DNS providers for Google Cloud DNS, Amazon Route53 & CoreDNS. AzureDNS is in progress. Generally they all work in native environment by auto detecting the configuration. But the initialisation is non- trivial in non-native environments say like in an on-premise cluster using Google Cloud DNS. The configuration has to be fed to the DNS Provider library in order to make it work properly. Each of this DNS provider has their own format for the configuration and has to be documented.

Additionally there is more work for AWS Route53 DNS provider. it does not use the user specified config as in [here](https://github.com/kubernetes/federation/blob/master/pkg/dnsprovider/providers/aws/route53/route53.go#L55).

/cc @kubernetes/sig-multicluster-misc

**Comment by shashidharatd** [comment]
There is some work done by @marun as commented in this kubernetes/kubernetes#40620 (comment) related to configuraing Google Cloud DNS in non-google environment.

**Comment by guoh1988** [comment]
# in  federation/pkg/federation-controller/service/dns/dns.go 177-192
func wantsDNSRecords(service *v1.Service) bool {
	return service.Spec.Type == v1.ServiceTypeLoadBalancer
}

func (s *ServiceDNSController) workerFunction() bool {
	item, quit := s.workQueue.Get()
	if quit {
		return true
	}
	defer s.workQueue.Done(item)

	service := item.(*v1.Service)

	if !wantsDNSRecords(service) {
		return false
}
#  Deploying federation control plane on non-cloud environment without loadbalancer 
and dns provider is coredns 
and k8s service type is nodeport ,
the problem is that coredns can not resolve service between two k8s-clusters
(e.g.)
#nslookup mysvc.default.myfed.svc.z1.r1.mydomain.com
