### ISSUE TITLE
RBAC roles error while joining Kubernetes cluster to the Federation

### ISSUE THREAD

**Issue by asad26** [kubernetes/federation#293]
Hi guys,
I am running one Federation cluster and one Kubernetes cluster (version 1.12.1) on two different Ubuntu 16.04 machines. The federation cluster (host cluster) is on the network 130.233.193.0/24 and the second cluster is on 130.233.97.0/23. I am unable to join the second cluster from host cluster using the command:

kubefed join cloud-cluster --host-cluster-context=kubernetes-admin-host --cluster-context=kubernetes-admin-cloud 

The following error appears:

**error:** Couldn't get clientset to create RBAC roles in the host cluster: Get https://130.233.97.82:6443/api: dial tcp 130.233.97.82:6443: i/o timeout

However, RBAC authorization is already enabled in api-server of both the clusters. Does anyone experience this type of error? If yes, please tell me how did you resolve it. To my understanding, I was thinking that it could be because of two different networks and there is a firewall in between them. Looking forward to your solutions.
Thanks

**Comment by shanesiebken** [comment]
The error there is an i/o timeout. It's possible that because of a connection failure, the federation plane was simply unable to resolve that the appropriate RBAC roles already exist on the target cluster. My first thought would be to confirm that all security settings allow for communication (in both directions) over the specified port.
